# Generated by Django 5.2.4 on 2025-08-05 18:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_default_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='professional_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
