# Generated by Django 5.2.4 on 2025-08-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='frequency',
        ),
        migrations.AddField(
            model_name='prescriptionmedication',
            name='dosage',
            field=models.CharField(default='500 mg', max_length=50),
        ),
        migrations.AddField(
            model_name='reminder',
            name='delivery_status',
            field=models.CharField(blank=True, help_text='Statut de livraison Twilio', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='error_message',
            field=models.TextField(blank=True, help_text="Message d'erreur en cas d'échec", null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='twilio_sid',
            field=models.CharField(blank=True, help_text='SID Twilio du message/appel', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('voice', 'Voice Call')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Livré'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
