# Generated by Django 5.2.4 on 2025-08-07 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_remove_medication_dosage_remove_medication_frequency_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='fds_appoint_patient_265d6c_idx',
            old_name='appointment_patient_75a4eb_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='fds_appoint_profess_78b046_idx',
            old_name='appointment_profess_480d0b_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='fds_appoint_schedul_bb68b7_idx',
            old_name='appointment_schedul_7cdd3a_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='fds_appoint_type_247b95_idx',
            old_name='appointment_type_2d073e_idx',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='fds_feedbac_patient_8850cb_idx',
            old_name='feedbacks_patient_eb3a37_idx',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='fds_feedbac_created_ad185c_idx',
            old_name='feedbacks_created_1c526e_idx',
        ),
        migrations.RenameIndex(
            model_name='prescription',
            new_name='fds_prescri_appoint_ecae9d_idx',
            old_name='prescriptio_appoint_6d01d6_idx',
        ),
        migrations.RenameIndex(
            model_name='reminder',
            new_name='fds_reminde_patient_4d4291_idx',
            old_name='reminders_patient_f08f32_idx',
        ),
        migrations.RenameIndex(
            model_name='reminder',
            new_name='fds_reminde_schedul_644b3c_idx',
            old_name='reminders_schedul_f9839e_idx',
        ),
        migrations.RenameIndex(
            model_name='reminder',
            new_name='fds_reminde_status_64b137_idx',
            old_name='reminders_status_9617ae_idx',
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='fds_appointments',
        ),
        migrations.AlterModelTable(
            name='department',
            table='fds_departments',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='fds_feedbacks',
        ),
        migrations.AlterModelTable(
            name='feedbacktheme',
            table='fds_feedback_themes',
        ),
        migrations.AlterModelTable(
            name='medication',
            table='fds_medications',
        ),
        migrations.AlterModelTable(
            name='prescription',
            table='fds_prescriptions',
        ),
        migrations.AlterModelTable(
            name='prescriptionmedication',
            table='fds_prescription_medications',
        ),
        migrations.AlterModelTable(
            name='reminder',
            table='fds_reminders',
        ),
    ]
