# Generated by Django 5.2.4 on 2025-07-31 13:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRecord',
            fields=[
                ('record_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('screening_results', models.CharField(choices=[('Valid', 'Valide'), ('Rejected', 'Rejeté'), ('Pending', 'En attente')], max_length=150)),
                ('record_date', models.DateField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Enregistrement de don',
                'verbose_name_plural': 'Enregistrements de don',
                'db_table': 'blood_record',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=2)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Donneur',
                'verbose_name_plural': 'Donneurs',
                'db_table': 'donor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('patient_history', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('prevision_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('prevision_date', models.DateField()),
                ('previsional_volume', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fiability', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
            ],
            options={
                'verbose_name': 'Prévision',
                'verbose_name_plural': 'Prévisions',
                'db_table': 'prevision',
                'ordering': ['-prevision_date'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('unit_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('collection_date', models.DateField()),
                ('volume_ml', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('hemoglobin_g_dl', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date_expiration', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Disponible'), ('Reserved', 'Réservé'), ('Expired', 'Expiré'), ('Used', 'Utilisé')], default='Available', max_length=50)),
                ('record', models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, to='app.bloodrecord')),
                ('donor', models.ForeignKey(db_column='donor_id', on_delete=django.db.models.deletion.CASCADE, to='app.donor')),
            ],
            options={
                'verbose_name': 'Unité de sang',
                'verbose_name_plural': 'Unités de sang',
                'db_table': 'blood_unit',
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('request_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('priority', models.CharField(choices=[('Routine', 'Routine'), ('Urgent', 'Urgent')], default='Routine', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'En attente'), ('Approved', 'Approuvé'), ('Rejected', 'Rejeté'), ('Fulfilled', 'Satisfait')], default='Pending', max_length=50)),
                ('request_date', models.DateField()),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('site', models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.CASCADE, to='app.site')),
            ],
            options={
                'verbose_name': 'Demande de sang',
                'verbose_name_plural': 'Demandes de sang',
                'db_table': 'blood_request',
                'ordering': ['-request_date', 'priority'],
            },
        ),
        migrations.AddField(
            model_name='bloodrecord',
            name='site',
            field=models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.CASCADE, to='app.site'),
        ),
        migrations.CreateModel(
            name='BloodConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='app.bloodrequest')),
                ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, to='app.bloodunit')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
            options={
                'verbose_name': 'Consommation de sang',
                'verbose_name_plural': 'Consommations de sang',
                'db_table': 'blood_consumption',
                'constraints': [models.UniqueConstraint(fields=('unit',), name='unique_unit_consumption')],
            },
        ),
    ]
